Fixed bug in default_max_snapshot initialization
When `snapshot_maximum` was None, casting to int
raised a ValueError.

```
ValueError: invalid literal for int() with base 10: ''
```

[DEV-16098]